ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- auth bypass
- authentication bypass
- rce
- remote code execution
- sql injection
- sqli
- privesc
- lfi
- local file inclusion
- rfi
- remote file inclusion
- remote escalation of privilege
- remote privilege escalation
- " sudo "
- " suid "
- " UAC "
- unauthenticated
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "

DESCRIPTION_KEYWORDS:
- NoneForNow
- User Account Control

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc

PRODUCT_KEYWORDS:
- " AEM "
- Adobe AEM
- AdobeCQ
- Adobe CQ
- Adobe Experience Platform
- Adobe Experience Manager
- Cisco
- Citrix
- Drupal
- Fortinet Fortigate
- IBM HTTP
- Juniper
- Microsoft Exchange
- Microsoft SQL
- Netscaler
- Pulse Secure
- Python Django
- Python Flask
- Spring Boot
- Tomcat
- VMware Horizon
- WordPress
