ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- rce
- remote code execution
- sql injection
- sqli
- privesc
- lfi
- local file inclusion
- rfi
- remote file inclusion
- high integrity
- remote escalation of privilege
- remote privilege escalation
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc
- podman
- container

PRODUCT_KEYWORDS:
- wordpress
- WordPress
- Drupal
- AEM
- Adobe AEM
- AdobeCQ
- Adobe CQ
- Adobe Experience Platform
- Adobe Experience Manager
- vCenter
- Oracle
- IBM HTTP
- Horizon
- Citrix
- Netscaler
- Pulse Secure
- Juniper
- Cisco
- Tomcat
- Microsoft Exchange
- Fortinet Fortigate
