# Search & Filtering Behavior
ALL_VALID: no
# Configure this as one of: all_cves, all_keywords, products
SEARCH_SCOPE: all_keywords
INCLUDE_HIGH_SEVERITY: True
HIGH_SEVERITY_THRESHOLD: 9.5

# Enable including only matched keywords if CVE is also a high CVSS score (reduce noise of low-severity CVE's)
# Disclaimer: If enabled, this means you will not see CVE's for which the CVSS score is currently blank
ENABLE_SCORE_FILTERING: True
MIN_SCORE_THRESHOLD: 6.0

# Update MITRE Exploit-DB dataset every 'n' days
MITRE_INTERVAL: 3

# If present, exclude CVE from results
EXCLUDED_KEYWORDS:
- SourceCodester

# Case-insensitive keywords in CVE Description/Summary
DESCRIPTION_KEYWORDS_I:
- auth bypass
- authentication bypass
- default credentials
- default password
- deserialization
- sql injection
- privesc
- local file inclusion
- remote file inclusion
- remote code execution
- " sudo "
- " suid "
- " UAC "
- docker
- kubernetes
- " lxc "

DESCRIPTION_KEYWORDS:
- User Account Control
- LFI
- RCE
- RFI
- SQLi

PRODUCT_KEYWORDS_I:
- kubernetes
- Microsoft O365

PRODUCT_KEYWORDS:
- " AEM "
- Adobe AEM
- AdobeCQ
- Adobe CQ
- Adobe Experience Platform
- Adobe Experience Manager
- Atlassian
- Cisco
- Citrix
- Confluence
- CrowdStrike
- Docker
- Fortinet Fortigate
- Groovy
- IBM HTTP
- Juniper
- Magento
- Microsoft Exchange
- Microsoft SQL
- Netscaler
- Pulse Secure
- Python Django
- Python Flask
- Spring Boot
- Spring Core
- Spring Security
- SwaggerUI
- Symantec Endpoint
- Tomcat
- Trend Micro
- VMware Horizon

# Repo's to exclude when crafting the Github CVE search URL
GITDORK_REPO_EXCLUSIONS:
- CVEProject/cvelist
- CVEProject/cvelistV5
- EXP-Tools/threat-broadcast
- Nazicc/threat-broadcast
- cloudsecurityalliance/gsd-database
- oasis-open/cti-stix-common-objects
- olbat/nvdcve
- ChuntBot/FeedArchive
- nomi-sec/NVD-Database
- github/advisory-database
- goncalor/cve-ark
- tholian-network/vulnerabilities
- sthagen/CVEProject-cvelist
- trickest/cve
- Patrowl/PatrowlHearsData
