# Search & Filtering Behavior
ALL_VALID: no
# Configure this as one of: all_cves, all_keywords, products
SEARCH_SCOPE: all_keywords
INCLUDE_HIGH_SEVERITY: True
HIGH_SEVERITY_THRESHOLD: 8.0

# Enable including only matched keywords if CVE is also a high CVSS score (reduce noise of low-severity CVE's)
ENABLE_SCORE_FILTERING: True
MIN_SCORE_THRESHOLD: 6.0

# If present, exclude CVE from results
EXCLUDED_KEYWORDS:
- SourceCodester

# Case-insensitive keywords in CVE Description/Summary
DESCRIPTION_KEYWORDS_I:
- auth bypass
- authentication bypass
- deserialization
- sql injection
- sqli
- privesc
- lfi
- local file inclusion
- rfi
- remote file inclusion
- rce
- remote code execution
- " sudo "
- " suid "
- " UAC "
- docker
- kubernetes
- " lxc "

DESCRIPTION_KEYWORDS:
- User Account Control

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc

PRODUCT_KEYWORDS:
- " AEM "
- Adobe AEM
- AdobeCQ
- Adobe CQ
- Adobe Experience Platform
- Adobe Experience Manager
- Cisco
- Citrix
- Drupal
- Fortinet Fortigate
- IBM HTTP
- Juniper
- Magento
- Microsoft Exchange
- Microsoft SQL
- Netscaler
- Pulse Secure
- Python Django
- Python Flask
- Spring Boot
- Tomcat
- VMware Horizon
- WordPress
